version: '3.8'
services:
  pg_container:
    container_name: pg_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cashmanager
    ports:
      - "5433:5432"
#  pgadmin_container:
#    container_name: pgadmin_container
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: root
#    ports:
#      - "5050:80"
  api_container:
    build:
      context: ../cashmanager
      dockerfile: ../cashmanager/Dockerfile
    container_name: api_container
    hostname: api_container
    ports:
      - "8080:8080"
    # stdin_open: true
    # tty: true
    # environment:
    #   SERVER_PORT: 8080
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://pg_container:5432/cashmanager
    #   SPRING_DATASOURCE_USERNAME: postgres
    #   SPRING_DATASOURCE_PASSWORD: root
    #   SPRING_JPA_HIBERNATE_DDL_AUTO: update
    # links:
    #   - pg_container
    depends_on:
      - pg_container


