name: front
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^0.23.0+1
  intl: ^0.17.0
  flutter_barcode_scanner: ^2.0.0
  nfc_manager: ^3.1.0
  fancy_bottom_navigation: ^0.3.2
  dio: ^4.0.4
  flutter_secure_storage: ^5.0.2
  country_icons: ^2.0.2
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/svg/
    - assets/images/
    - .env

  fonts:
    - family: Avenir
      fonts:
          - asset: assets/fonts/Avenir-Black.ttf
            weight: 900
          - asset: assets/fonts/Avenir-Heavy.ttf
            weight: 700
          - asset: assets/fonts/Avenir-Medium.ttf
            weight: 500
          - asset: assets/fonts/Avenir-Light.ttf
            weight: 300
    - family: AppIcons
      fonts:
        - asset: assets/fonts/app_icons.ttf
